service: url-shortener
provider:
  name: aws
  runtime: nodejs12.0
  stage: dev
  region: us-east-1

function:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: `ANY {proxy+}`